### ISSUE TITLE
How much GPU memory needed?

### ISSUE THREAD

**Issue by dedoogong** [kalpitthakkar/pb-gcn#1]
I tried to run training with batch size 1 or 2, but it shows "Cannot allocate memory" error after occupying some GPU global memory around 5~700MB. I have 2 GPUs-GTX1080. 

Thank you~!

**Comment by kalpitthakkar** [comment]
This is unusual.
I tried running my network with a batch size of 4 on 4 Titan Xp. It occupies ~1G of memory per GPU when the training starts and this memory profile persists. A batch of 64 on 4 Titan Xp shows a memory occupancy of ~9G per GPU.

GTX 1080 has 8G of memory, so according to what I know, the largest batch size that should work on 2 1080s would be 30.

My first guess would be either NVIDIA driver or CUDA / CuDNN version problem.
To make sure, I have tested my code with Pytorch 1.1.0 using CUDA 9.0 (build py3.6_cuda9.0.176_cudnn7.5.1_0). You can start investigating there.

**Comment by dedoogong** [comment]
yes you are right. I will close this issue.
