### ISSUE TITLE
Questions about HDM05 dataset

### ISSUE THREAD

**Issue by hoyeYang** [kalpitthakkar/pb-gcn#4]
Hi, thanks for your great contribution!
Could you give me some details about how to preprocess the HDM05 dataset or offer processed .mat files of HDM05 dataset? In fact, when I was going to preprocess the HDM05 dataset, I couldn't tell which data (the full takes or the cuts) did you download and whch file (.c3d or .amc) did you use to generate .mat file?

**Comment by kalpitthakkar** [comment]
Hello!

You can download the HDM05 dataset preprocessed and converted to .mat files from this [Google Drive link](https://drive.google.com/open?id=1G1XDHPt4WE57jACiGe2sOm2k-mS1tKcL). You can use these files with the `prepare_hdm05.py` script to generate the required input videos and labels.

I am sorry for not uploading this before and the delay in responding.

**Comment by hoyeYang** [comment]
Thanks a lot!
