### ISSUE TITLE
about path

### ISSUE THREAD

**Issue by binggan-1-ui** [kalpitthakkar/pb-gcn#6]
Could you give me a detailed explanation of the path，  
For example,work_dir，  data_path ，missing_txt  and   split_dir

**Comment by kalpitthakkar** [comment]
@binggan-1-ui The meaning of these paths are as follows:

`work_dir` is the path to the folder where all the summary and metrics are stored, related to the model being trained.

`data_path` is the path to the original skeleton data downloaded and arranged. For example: Have a look at this [data prep script](https://github.com/kalpitthakkar/pb-gcn/blob/master/utils/nturgbd/prepare_ntu.py). You will understand the meaning of `missing_txt` as well.

`split_dir` is basically the path to folder that contains `train_data.npy` and `train_label.pkl` prepared from the data prep scripts.
