### ISSUE TITLE
question about Hdm05

### ISSUE THREAD

**Issue by dcygoodboy** [kalpitthakkar/pb-gcn#8]
I got a question for you, How can I execute the HMD05 dataset?

**Comment by kalpitthakkar-lm** [comment]
@dcygoodboy What do you mean?
Can you elaborate a bit please?

**Comment by kalpitthakkar** [comment]
@dcygoodboy Execution details are already provided for both NTURGB+D and HDM05. Please go through them and ask a specific question if you have any.
